import Footer from "@/pages/footer";
import "./globals.css";
import Header from "@/pages/header";
import { Providers } from "@/redux/provider";

export const metadata = {
  title: "web portal for mobile phones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
