import Footer from "@/pages/footer";
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/pages/header";

// const inter = Poppins({ subsets: ["devanagari"] });
// const inter = Poppins({ subsets: ["latin"] });

export const metadata = {
  title: "web portal for mobile phones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
